@extends('layouts.app')
@section('title', 'Invoice Pengiriman')
@section('content')
<div class="mb-5 flex items-start justify-between gap-3"><div><h1 class="text-2xl md:text-3xl font-black">Invoice Harian</h1><p class="text-sm text-slate-500 mt-1">Pencatatan pengiriman ikan per kapal.</p></div><a href="{{ route('invoices.create') }}" class="rounded-2xl bg-teal-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-teal-700/20">Tambah</a></div>
<form method="GET" data-allow-multi-submit="true" class="mb-4 rounded-[1.5rem] bg-white p-3 md:p-4 shadow-sm border border-slate-100 grid grid-cols-2 md:grid-cols-5 gap-2 md:gap-3 text-sm">
    <select name="ship_id" class="min-h-[48px] rounded-2xl border-slate-200 bg-slate-50 px-3 text-base"><option value="">Semua kapal</option>@foreach($ships as $ship)<option value="{{ $ship->id }}" @selected(request('ship_id') == $ship->id)>{{ $ship->name }}</option>@endforeach</select>
    <select name="status" class="min-h-[48px] rounded-2xl border-slate-200 bg-slate-50 px-3 text-base"><option value="">Semua status</option>@foreach(['draft' => 'Draft', 'posted' => 'Sudah Diposting', 'closed' => 'Sudah Ditutup', 'cancelled' => 'Dibatalkan'] as $status => $label)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $label }}</option>@endforeach</select>
    <input type="number" name="month" value="{{ request('month') }}" min="1" max="12" placeholder="Bulan" class="min-h-[48px] rounded-2xl border-slate-200 bg-slate-50 px-4 text-base">
    <input type="number" name="year" value="{{ request('year', now()->year) }}" placeholder="Tahun" class="min-h-[48px] rounded-2xl border-slate-200 bg-slate-50 px-4 text-base">
    <button class="col-span-2 md:col-span-1 rounded-2xl bg-[#073b3a] text-white px-4 py-3 font-bold">Saring</button>
</form>
<div class="space-y-3 md:hidden">@forelse($invoices as $invoice)<a href="{{ route('invoices.show', $invoice) }}" class="block rounded-[1.5rem] bg-white p-4 shadow-sm border border-slate-100"><div class="flex justify-between gap-3"><div class="min-w-0"><div class="font-black text-teal-700 truncate">{{ $invoice->invoice_number }}</div><div class="text-xs text-slate-500 mt-1">{{ $invoice->invoice_date->format('d/m/Y') }} · {{ $invoice->ship?->name }}</div></div><span class="rounded-full px-3 py-1 text-[11px] font-bold h-fit bg-slate-100 text-slate-700">{{ $invoice->status_label }}</span></div><div class="grid grid-cols-3 gap-2 mt-4 text-sm"><div><div class="text-[11px] text-slate-400">Gabus</div><div class="font-bold">{{ $invoice->total_boxes }}</div></div><div><div class="text-[11px] text-slate-400">Masuk</div><div class="font-bold">{{ \App\Support\Money::rupiah($invoice->total_income) }}</div></div><div><div class="text-[11px] text-slate-400">Bersih</div><div class="font-bold text-green-700">{{ \App\Support\Money::rupiah($invoice->net_income) }}</div></div></div></a>@empty<div class="rounded-[1.5rem] bg-white p-8 text-center text-slate-500">Belum ada invoice.</div>@endforelse</div>
<div class="hidden md:block rounded-[1.5rem] bg-white shadow-sm border border-slate-100 overflow-hidden"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">Nomor</th><th class="p-4 text-left">Tanggal</th><th class="p-4 text-left">Kapal</th><th class="p-4 text-right">Gabus</th><th class="p-4 text-right">Pemasukan</th><th class="p-4 text-right">Pengeluaran</th><th class="p-4 text-right">Bersih</th><th class="p-4 text-left">Keadaan</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr class="border-t border-slate-100"><td class="p-4"><a href="{{ route('invoices.show', $invoice) }}" class="text-teal-700 font-bold">{{ $invoice->invoice_number }}</a></td><td class="p-4">{{ $invoice->invoice_date->format('d/m/Y') }}</td><td class="p-4">{{ $invoice->ship?->name }}</td><td class="p-4 text-right">{{ $invoice->total_boxes }}</td><td class="p-4 text-right">{{ \App\Support\Money::rupiah($invoice->total_income) }}</td><td class="p-4 text-right">{{ \App\Support\Money::rupiah($invoice->total_expense) }}</td><td class="p-4 text-right font-bold">{{ \App\Support\Money::rupiah($invoice->net_income) }}</td><td class="p-4">{{ $invoice->status_label }}</td></tr>@empty<tr><td colspan="8" class="p-8 text-center text-slate-500">Belum ada invoice.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $invoices->links() }}</div>
@endsection
