<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><title>Print Invoice {{ $invoice->invoice_number }}</title><style>body{font-family:Arial,sans-serif;font-size:13px;color:#111}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ddd;padding:8px}th{background:#f4f4f4;text-align:left}.right{text-align:right}.summary{margin-top:16px;width:45%;margin-left:auto}@media print{button{display:none}}</style></head><body>
<button onclick="window.print()">Print</button>
<h2>Invoice Pengiriman Ikan</h2>
<p><strong>Nomor:</strong> {{ $invoice->invoice_number }}<br><strong>Tanggal:</strong> {{ $invoice->invoice_date->format('d/m/Y') }}<br><strong>Kapal:</strong> {{ $invoice->ship?->name }}<br><strong>Kapten:</strong> {{ $invoice->captain?->name }}<br><strong>Kapal Ongkir:</strong> {{ $invoice->carrier_boat_name }}<br><strong>Status:</strong> {{ strtoupper($invoice->status) }}</p>
<h3>Detail Pembeli</h3><table><thead><tr><th>Pembeli</th><th>Jenis Ikan</th><th class="right">Gabus</th><th class="right">Harga/Gabus</th><th class="right">Subtotal</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->buyer?->name }}</td><td>{{ $item->fish_type }}</td><td class="right">{{ $item->box_count }}</td><td class="right">{{ \App\Support\Money::rupiah($item->price_per_box) }}</td><td class="right">{{ \App\Support\Money::rupiah($item->subtotal) }}</td></tr>@endforeach</tbody></table>
<h3>Pengeluaran</h3><table><thead><tr><th>Jenis</th><th>Deskripsi</th><th class="right">Qty</th><th class="right">Total</th></tr></thead><tbody>@foreach($invoice->expenses as $expense)<tr><td>{{ $expense->expense_type }}</td><td>{{ $expense->description }}</td><td class="right">{{ $expense->quantity }}</td><td class="right">{{ \App\Support\Money::rupiah($expense->amount) }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><th>Total Pemasukan</th><td class="right">{{ \App\Support\Money::rupiah($invoice->total_income) }}</td></tr><tr><th>Total Pengeluaran</th><td class="right">{{ \App\Support\Money::rupiah($invoice->total_expense) }}</td></tr><tr><th>Pendapatan Bersih</th><td class="right"><strong>{{ \App\Support\Money::rupiah($invoice->net_income) }}</strong></td></tr></table>
</body></html>
